import csv, math, os, random, tempfile, unittest

import effort_calibration as ec


def synthetic_workouts(prm, n, seed, person="S", noise=0.15):
    """Workouts whose WHOOP strain is generated by the model itself, across all four bands."""
    rng = random.Random(seed)
    out = []
    for i in range(n):
        kind = i % 4  # light, moderate, hard, very hard: keeps every band populated
        minutes = [rng.uniform(10, 40), rng.uniform(30, 90), rng.uniform(45, 150), rng.uniform(90, 300)][kind]
        raw = [rng.random() ** (3 - kind * 0.6) for _ in range(5)]
        if kind >= 2:
            raw = raw[:2] + [r * (1 + kind) for r in raw[2:]]
        below = rng.uniform(0.0, 0.4) if kind == 0 else rng.uniform(0.0, 0.1)
        total = sum(raw)
        shares = [(1 - below) * r / total for r in raw]
        w = {"person": person, "day": float(i), "month": "", "minutes": minutes, "below": below, "shares": shares,
             "mids": ec.DEFAULT_MIDPOINTS, "old_zones": False}
        w["strain"] = round(min(20.99, max(0.0, ec.predict(w, prm) + rng.gauss(0, noise))), 1)
        w["edwards"] = minutes * sum(s * ec.edwards_weight(x) for s, x in zip(shares, w["mids"]))
        out.append(w)
    return out


class TodayFormula(unittest.TestCase):
    def test_matches_noop_log_map(self):
        # NOOP: Effort = 100 x ln(TRIMP + 1) / ln(7201), shown x 21/100 on the WHOOP axis.
        self.assertAlmostEqual(ec.today_score(372), 21 * math.log(373) / math.log(7201), places=9)
        self.assertAlmostEqual(ec.today_score(7200), 21.0, places=9)
        self.assertEqual(ec.today_score(0), 0.0)

    def test_edwards_weights(self):
        self.assertEqual([ec.edwards_weight(x) for x in (45, 50, 59.9, 60, 75, 89.9, 90, 100)], [0, 1, 1, 2, 3, 4, 5, 5])


class Curve(unittest.TestCase):
    prm = {"a": 5.4, "k": 13.0, "beta": 0.6, "w0": 0.5, "p": ec.P_CAP}

    def test_monotonic_and_never_21(self):
        values = [ec.curve(t, self.prm) for t in (0, 1, 10, 100, 1000, 10_000, 1e6, 1e12)]
        self.assertEqual(values, sorted(values))
        self.assertTrue(all(v < 21.0 for v in values))
        self.assertEqual(values[0], 0.0)

    def test_large_exponent_does_not_overflow(self):
        self.assertLess(ec.curve(1e9, dict(self.prm, p=400.0)), 21.0)


class Info(unittest.TestCase):
    def test_page_comment(self):
        info = ec.parse_info("- Max HR setting in WHOOP: manual 196\n"
                             "- Custom HR zones in WHOOP: yes, lower bounds (bpm): Z1 122, Z2 140, Z3 152, Z4 165, Z5 178\n"
                             "- Workouts imported from another device (Strava, a watch, Apple Health): not sure\n")
        self.assertEqual((info["maxhr_mode"], info["maxhr"]), ("manual", 196.0))
        self.assertEqual((info["zones"], info["bounds"]), ("yes", [122.0, 140.0, 152.0, 165.0, 178.0]))
        self.assertEqual(info["imported"], "unknown")

    def test_not_sure_is_not_no(self):
        info = ec.parse_info("- Custom HR zones in WHOOP: not sure\n- Max HR setting in WHOOP: auto\n")
        self.assertEqual((info["zones"], info["maxhr_mode"], info["maxhr"]), ("unknown", "auto", None))

    def test_incomplete_bounds_are_not_used(self):
        info = ec.parse_info("- Custom HR zones in WHOOP: yes, lower bounds (bpm): Z1 122, Z2 140, Z3 ?, Z4 ?, Z5 ?\n")
        self.assertEqual((info["zones"], info["bounds"]), ("yes", None))


class Preparation(unittest.TestCase):
    def test_strength_names_in_several_languages(self):
        for name in ("Weightlifting", "Gewichtheben", "Strength-Trainer", "Musculación", "Musculação", "Powerlifting"):
            self.assertTrue(ec.is_strength(name), name)
        for name in ("Running", "Spazieren", "Crosstrainer", "Cycling", "Aktivität"):
            self.assertFalse(ec.is_strength(name), name)

    def test_default_bounds_map_to_default_midpoints(self):
        rhr, hrmax = 60.0, 190.0
        bounds = [rhr + f * (hrmax - rhr) for f in (0.5, 0.6, 0.7, 0.8, 0.9)]
        mids = ec.zone_midpoints({"zones": "yes", "bounds": bounds}, rhr, hrmax)
        for got, want in zip(mids, ec.DEFAULT_MIDPOINTS):
            self.assertAlmostEqual(got, want, places=6)

    def test_custom_zones_without_bounds_cannot_be_placed(self):
        self.assertIsNone(ec.zone_midpoints({"zones": "yes", "bounds": None}, 60, 190))

    def test_trailing_hrmax_follows_recent_peaks(self):
        days = [{"day": str(d), "max_hr": str(m)} for d, m in [(0, 200), (10, 198), (50, 190), (150, 182), (160, 181)]]
        at = ec.trailing_hrmax(days, window=90)
        self.assertEqual(at(60), 198)   # 200, 198, 190 in window -> second highest
        self.assertEqual(at(170), 181)  # old peaks have left the window
        self.assertEqual(at(0), 200)    # only one value available


class ZoneSwitch(unittest.TestCase):
    def rows(self, n_old, n_new, seed=3):
        rng, rows = random.Random(seed), []
        for i in range(n_old + n_new):
            rhr, hrmax = 64.0, 196.0
            shares = [rng.random() for _ in range(5)]
            total = sum(shares)
            shares = [s / total for s in shares]
            mids = ([m * hrmax for m in ec.MAXHR_MIDPOINTS] if i < n_old
                    else [rhr + m * (hrmax - rhr) for m in ec.MAXHR_MIDPOINTS])
            avg = sum(s * m for s, m in zip(shares, mids)) + rng.gauss(0, 2)
            rows.append((float(i), shares, avg, rhr, hrmax))
        return rows

    def test_finds_the_switch(self):
        day, gain = ec.find_zone_switch(self.rows(60, 60))
        self.assertIsNotNone(day)
        self.assertLessEqual(abs(day - 60), 2)
        self.assertGreater(gain, 0.5)

    def test_no_switch_when_all_new(self):
        day, _ = ec.find_zone_switch(self.rows(0, 80))
        self.assertIsNone(day)


class Fitting(unittest.TestCase):
    def test_recovers_several_injected_parameter_sets(self):
        # CLAUDE.md: prove the method tracks a varying input, not one lucky match.
        for truth in ({"a": 5.4, "k": 13.0, "beta": 0.60, "w0": 0.5, "p": ec.P_CAP},
                      {"a": 4.0, "k": 25.0, "beta": 0.85, "w0": 0.2, "p": ec.P_CAP}):
            with self.subTest(truth=truth):
                data = synthetic_workouts(truth, 240, seed=int(truth["k"]))
                got = ec.fit(data)
                for name, minutes in ec.SCENARIOS:
                    self.assertAlmostEqual(ec.scenario(minutes, got)[1], ec.scenario(minutes, truth)[1], delta=0.5, msg=name)
                self.assertAlmostEqual(got["beta"], truth["beta"], delta=0.1)

    def test_band_balance_keeps_hard_workouts_right(self):
        truth = {"a": 5.4, "k": 13.0, "beta": 0.6, "w0": 0.5, "p": ec.P_CAP}
        data = synthetic_workouts(truth, 240, seed=7)
        light = [w for w in data if ec.band(w["strain"]) == "light"]
        hard = [w for w in data if w["strain"] >= 14]
        data = light * 8 + hard  # swamp the hard workouts, as a real export does
        e = ec.evaluate(data, ec.fit(data))
        self.assertLess(abs(e["top_bias_new"]), 0.5)

    def test_leave_one_out_scores_each_person_without_their_data(self):
        truth = {"a": 5.4, "k": 13.0, "beta": 0.6, "w0": 0.5, "p": ec.P_CAP}
        people = {p: synthetic_workouts(truth, 120, seed=s, person=p) for p, s in (("A", 1), ("B", 2), ("C", 3))}
        results = ec.leave_one_out(people)
        self.assertEqual(set(results), {"A", "B", "C"})
        self.assertTrue(all(ec.passes(e) for e in results.values()))


class EndToEnd(unittest.TestCase):
    def test_report_from_share_files(self):
        truth = {"a": 5.4, "k": 13.0, "beta": 0.6, "w0": 0.5, "p": ec.P_CAP}
        with tempfile.TemporaryDirectory() as root:
            for person, seed in (("A", 11), ("B", 12)):
                folder = os.path.join(root, person)
                os.makedirs(folder)
                data = synthetic_workouts(truth, 80, seed=seed)
                with open(os.path.join(folder, "whoop_workouts_shared.csv"), "w", newline="") as f:
                    w = csv.writer(f)
                    w.writerow(["day", "month", "activity", "duration_min", "strain", "max_hr", "avg_hr", "z1", "z2", "z3", "z4", "z5"])
                    for x in data:
                        w.writerow([int(x["day"]), "2026-01", "Running", round(x["minutes"], 1), x["strain"], 180, "",
                                    *(round(s * 100, 1) for s in x["shares"])])
                    w.writerow([0, "2026-01", "Weightlifting", 60, 9.0, 150, 120, 20, 30, 30, 10, 0])
                with open(os.path.join(folder, "whoop_days_shared.csv"), "w", newline="") as f:
                    w = csv.writer(f)
                    w.writerow(["day", "month", "day_strain", "resting_hr", "max_hr", "avg_hr"])
                    for x in data:
                        w.writerow([int(x["day"]), "2026-01", 12.0, 60, 185, 80])
                with open(os.path.join(folder, "info.txt"), "w") as f:
                    f.write("- Max HR setting in WHOOP: auto\n- Custom HR zones in WHOOP: no\n")
            text = ec.report(root)
        self.assertIn("leave-one-out", text)
        self.assertIn("1 strength", text)
        self.assertIn("| A |", text)
        self.assertIn("Marathon", text)


if __name__ == "__main__":
    unittest.main()
